### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by IsanHu** [googlesamples/google-photos#12]
Hi 
I can't get through `Sign in with Google`
![image](https://user-images.githubusercontent.com/3689943/50162083-69c30e00-0318-11e9-940e-3a8cfca27499.png)

My credentials:
```
{
    "web": {
        "client_id": "my client id",
        "project_id": "my project id",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://www.googleapis.com/oauth2/v3/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "my client secret",
        "redirect_uris": [
            "http://127.0.0.1:8080/auth/google/callback"
        ],
        "javascript_origins": [
            "http://127.0.0.1"
        ]
    }
}
```

I got `InternalOAuthError: Failed to obtain access token`
```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/Users/isan/Downloads/google-photos-master/REST/PhotoFrame/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /Users/isan/Downloads/google-photos-master/REST/PhotoFrame/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/isan/Downloads/google-photos-master/REST/PhotoFrame/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/Users/isan/Downloads/google-photos-master/REST/PhotoFrame/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by abdellahaski** [comment]
Same here any updates ?
