### ISSUE TITLE
Deploy in heroku fails

### ISSUE THREAD

**Issue by pinamahn3** [googlesamples/google-photos#24]
I edited the `package.json `as follows and tried to deploy to heroku NPM. Could you please help?

1. Fails also without DEBUG=TRUE
2. Build succeeds but deploy fails
3. I put appropriate values for clientID and secret in config.js, URL. 
``` 
REST/PhotoFrame/config.js 
config.oAuthClientID  config.oAuthclientSecret 
config.oAuthCallbackUrl = 'https://REDACTED.herokuapp.com/auth/google/callback';
```

5.
```
 The port where the app should listen for requests.
config.port = 443;
```

The file: 

```
cat  package.json 
{
  "name": "photo-frame-sample",
  "version": "1.0.0",
  "description": "Google Photos Library API photo frame sample",
  "private": true,
  "license": "Apache-2.0",
  "author": "Google LLC",
  "repository": {
    "type": "git",
    "url": "https://github.com/googlesamples/google-photos.git"
  },
  "main": "app.js",
  "type": "module",
  "dependencies": {
    "@fancyapps/fancybox": "^3.5.7",
    "body-parser": "^1.19.1",
    "ejs": "^3.1.6",
    "express": "^4.17.2",
    "express-session": "^1.17.2",
    "express-winston": "^4.2.0",
    "jquery": "^3.6.0",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.3.0",
    "node-fetch": "^3.1.0",
    "node-persist": "^3.1.0",
    "passport": "^0.5.2",
    "passport-google-oauth20": "^2.0.0",
    "session-file-store": "^1.5.0",
    "winston": "^3.3.3"
  },
  "scripts": {
    "start": "DEBUG=TRUE node REST/PhotoFrame/app.js"
  },
  "engines": {
    "node": "14.x"
  }
}
```

```
 heroku[web.1]: State changed from crashed to starting
 app[api]: Build succeeded
 heroku[web.1]: Starting process with command `npm start`
 app[web.1]: 
 app[web.1]: > photo-frame-sample@1.0.0 start /app
 app[web.1]: > DEBUG=TRUE node REST/PhotoFrame/app.js
 app[web.1]: 
 app[web.1]: events.js:377
 app[web.1]: throw er; // Unhandled 'error' event
 app[web.1]: ^
 app[web.1]: 
 app[web.1]: Error: listen EACCES: permission denied 0.0.0.0:443
 app[web.1]: at Server.setupListenHandle [as _listen2] (net.js:1314:21)
 app[web.1]: at listenInCluster (net.js:1379:12)
 app[web.1]: at Server.listen (net.js:1465:7)
 app[web.1]: at file:///app/REST/PhotoFrame/app.js:398:8
 app[web.1]: at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
 app[web.1]: at async Loader.import (internal/modules/esm/loader.js:178:24)
 app[web.1]: at async Object.loadESM (internal/process/esm_loader.js:68:5)
 app[web.1]: at async handleMainPromise (internal/modules/run_main.js:59:12)
 app[web.1]: Emitted 'error' event on Server instance at:
 app[web.1]: at emitErrorNT (net.js:1358:8)
 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:82:21) {
 app[web.1]: code: 'EACCES',
 app[web.1]: errno: -13,
 app[web.1]: syscall: 'listen',
 app[web.1]: address: '0.0.0.0',
 app[web.1]: port: 443
 app[web.1]: }
 app[web.1]: npm ERR! code ELIFECYCLE
 app[web.1]: npm ERR! errno 1
 app[web.1]: npm ERR! photo-frame-sample@1.0.0 start: `DEBUG=TRUE node REST/PhotoFrame/app.js`
 app[web.1]: npm ERR! Exit status 1
 app[web.1]: npm ERR!
 app[web.1]: npm ERR! Failed at the photo-frame-sample@1.0.0 start script.
 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 app[web.1]: 
 app[web.1]: npm ERR! A complete log of this run can be found in:
 app[web.1]: npm ERR!     /app/.npm/_logs/2022-05-01T16_39_40_608Z-debug.log
 heroku[web.1]: Process exited with status 1
 heroku[web.1]: State changed from starting to crashed
```

**Comment by jfschmakeit** [comment]
This seems to be an issue with Heroku or your set up, which sounds like it might be out of scope for us to support.

Looking at the logging output, it appears that you do not have permission to bind to port 443:
```
 app[web.1]: Error: listen EACCES: permission denied 0.0.0.0:443
```
 While this port is hardcoded in the app itself, heroku appears to expect a different port as specified as an environment variable. You might find this troubleshooting guide helpful: https://devcenter.heroku.com/articles/troubleshooting-node-deploys#incorrect-port-setup 

Just note that the _authorized redirect URL_ should match your final deployed URL where your application will be running.
